# -*- coding: utf-8 -*-
"""League of Legends Match Predictor_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e98thc2VKNzQ6kmY6vfDchxJvFVmtfOT

### Introduction

League of Legends, a popular multiplayer online battle arena (MOBA) game, generates extensive data from matches, providing an excellent opportunity to apply machine learning techniques to real-world scenarios. Perform the following steps to build a logistic regression model aimed at predicting the outcomes of League of Legends matches.

Use the [league_of_legends_data_large.csv](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/rk7VDaPjMp1h5VXS-cUyMg/league-of-legends-data-large.csv) file to perform the tasks.

### Step 1: Data Loading and Preprocessing

#### Task 1: Load the League of Legends dataset and preprocess it for training.

Loading and preprocessing the dataset involves reading the data, splitting it into training and testing sets, and standardizing the features. You will utilize `pandas` for data manipulation, `train_test_split` from `sklearn` for data splitting, and `StandardScaler` for feature scaling.

Note: Please ensure all the required libraries are installed and imported.

1 .Load the dataset:
Use `pd.read_csv()` to load the dataset into a pandas DataFrame.</br>
2. Split data into features and target: Separate win (target) and the remaining columns (features).</br>
   X = data.drop('win', axis=1)</br>
   y = data['win'] </br>
3 .Split the Data into Training and Testing Sets:
Use `train_test_split()` from `sklearn.model_selection` to divide the data. Set `test_size`=0.2 to allocate 20% for testing and 80% for training, and use `random_state`=42 to ensure reproducibility of the split.</br>
4. Standardize the features:
Use `StandardScaler()` from sklearn.preprocessing to scale the features.</br>
5. Convert to PyTorch tensors:
Use `torch.tensor()` to convert the data to PyTorch tensors.

#### Exercise 1:

Write a code to load the dataset, split it into training and testing sets, standardize the features, and convert the data into PyTorch tensors for use in training a PyTorch model.

### Setup
Installing required libraries:

The following required libraries are not pre-installed in the Skills Network Labs environment. You will need to run the following cell to install them:
"""

!pip install pandas
!pip install scikit-learn
!pip install torch
!pip install matplotlib

"""### Step 2: Logistic Regression Model

#### Task 2: Implement a logistic regression model using PyTorch.

Defining the logistic regression model involves specifying the input dimensions, the forward pass using the sigmoid activation function, and initializing the model, loss function, and optimizer.

1 .Define the Logistic Regression Model:</br>
  Create a class LogisticRegressionModel that inherits from torch.nn.Module.</br>
 - In the `__init__()` method, define a linear layer (nn.Linear) to implement the logistic regression model.</br>
- The `forward()` method should apply the sigmoid activation function to the output of the linear layer.</br>

2.Initialize the Model, Loss Function, and Optimizer:</br>
- Set input_dim: Use `X_train.shape[1]` to get the number of features from the training data (X_train).</br>
- Initialize the model: Create an instance of the LogisticRegressionModel class  (e.g., `model = LogisticRegressionModel()`)while passing input_dim as a parameter</br>
- Loss Function: Use `BCELoss()` from torch.nn (Binary Cross-Entropy Loss).</br>
- Optimizer: Initialize the optimizer using `optim.SGD()` with a learning rate of 0.01</br>

#### Exercise 2:

Define the logistic regression model using PyTorch, specifying the input dimensions and the forward pass. Initialize the model, loss function, and optimizer.

### Step 3: Model Training

#### Task 3: Train the logistic regression model on the dataset.

The training loop will run for a specified number of epochs. In each epoch, the model makes predictions, calculates the loss, performs backpropagation, and updates the model parameters.

1. Set Number of Epochs:  
   - Define the number of epochs for training to 1000.

2. Training Loop:  
   For each epoch:
   - Set the model to training mode using `model.train()`.
   - Zero the gradients using `optimizer.zero_grad()`.
   - Pass the training data (`X_train`) through the model to get the predictions (`outputs`).
   - Calculate the loss using the defined loss function (`criterion`).
   - Perform backpropagation with `loss.backward()`.
   - Update the model's weights using `optimizer.step()`.

3. Print Loss Every 100 Epochs:  
   - After every 100 epochs, print the current epoch number and the loss value.

4. Model Evaluation:  
   - Set the model to evaluation mode using `model.eval()`.
   - Use `torch.no_grad()` to ensure no gradients are calculated during evaluation.
   - Get predictions on both the training set (`X_train`) and the test set (`X_test`).

5. Calculate Accuracy:  
   - For both the training and test datasets, compute the accuracy by comparing the predicted values with the true values (`y_train`, `y_test`).
   - Use a threshold of 0.5 for classification
   
6. Print Accuracy:  
   - Print the training and test accuracies after the evaluation is complete.

#### Exercise 3:

Write the code to train the logistic regression model on the dataset. Implement the training loop, making predictions, calculating the loss, performing backpropagation, and updating model parameters. Evaluate the model's accuracy on training and testing sets.

### Step 4: Model Optimization and Evaluation

#### Task 4: Implement optimization techniques and evaluate the model's performance.

Optimization techniques such as L2 regularization (Ridge Regression) help in preventing overfitting. The model is retrained with these optimizations, and its performance is evaluated on both training and testing sets.

**Weight Decay** :In the context of machine learning and specifically in optimization algorithms, weight_decay is a parameter used to apply L2 regularization to the model's parameters (weights). It helps prevent the model from overfitting by penalizing large weight values, thereby encouraging the model to find simpler solutions.To use L2 regularization, you need to modify the optimizer by setting the weight_decay parameter. The weight_decay parameter in the optimizer adds the L2 regularization term during training.
For example, when you initialize the optimizer with optim.SGD(model.parameters(), lr=0.01, weight_decay=0.01), the weight_decay=0.01 term applies L2 regularization with a strength of 0.01.

1. Set Up the Optimizer with L2 Regularization:
   - Modify the optimizer to include `weight_decay` for L2 regularization.
   - Example:
     ```python
     optimizer = optim.SGD(model.parameters(), lr=0.01, weight_decay=0.01)
     ```
2. Train the Model with L2 Regularization:
    - Follow the same steps as before but use the updated optimizer with regularization during training.
    - Use epochs=1000
   
3. Evaluate the Optimized Model:
   - After training, evaluate the model on both the training and test datasets.
   - Compute the accuracy for both sets by comparing the model's predictions to the true labels (`y_train` and `y_test`).

4. Calculate and Print the Accuracy:
   - Use a threshold of 0.5 to determine whether the model's predictions are class 0 or class 1.
   - Print the training accuracy and test accuracy  after evaluation.


#### Exercise 4:

Implement optimization techniques like L2 regularization and retrain the model. Evaluate the performance of the optimized model on both training and testing sets.

### Step 5: Visualization and Interpretation

Visualization tools like confusion matrices and ROC curves provide insights into the model's performance. The confusion matrix helps in understanding the classification accuracy, while the ROC curve illustrates the trade-off between sensitivity and specificity.

Confusion Matrix : A Confusion Matrix is a fundamental tool used in classification problems to evaluate the performance of a model. It provides a matrix showing the number of correct and incorrect predictions made by the model, categorized by the actual and predicted classes.
Where
-  True Positive (TP): Correctly predicted positive class (class 1).
- True Negative (TN): Correctly predicted negative class (class 0).
- False Positive (FP): Incorrectly predicted as positive (class 1), but the actual class is negative (class 0). This is also called a Type I error.
- False Negative (FN): Incorrectly predicted as negative (class 0), but the actual class is positive (class 1). This is also called a Type II error.

ROC Curve (Receiver Operating Characteristic Curve):
The ROC Curve is a graphical representation used to evaluate the performance of a binary classification model across all classification thresholds. It plots two metrics:
- True Positive Rate (TPR) or Recall (Sensitivity)-It is the proportion of actual positive instances (class 1) that were correctly classified as positive by the model.
- False Positive Rate (FPR)-It is the proportion of actual negative instances (class 0) that were incorrectly classified as positive by the model.
  
AUC:
AUC stands for Area Under the Curve and is a performance metric used to evaluate the quality of a binary classification model. Specifically, it refers to the area under the ROC curve (Receiver Operating Characteristic curve), which plots the True Positive Rate (TPR) versus the False Positive Rate (FPR) for different threshold values.

Classification Report:
A Classification Report is a summary of various classification metrics, which are useful for evaluating the performance of a classifier on the given dataset.

#### Exercise 5:

Write code to visualize the model's performance using confusion matrices and ROC curves. Generate classification reports to evaluate precision, recall, and F1-score. Retrain the model with L2 regularization and evaluate the performance.
"""

# #Change the name of variables as per your code
# import matplotlib.pyplot as plt
# from sklearn.metrics import confusion_matrix, classification_report, roc_curve, auc
# import itertools

# # Visualize the confusion matrix
# #Change the variable names as used in your code
# y_pred_test_labels = (y_pred_test > 0.5).float()
# cm = confusion_matrix(y_test, y_pred_test_labels)

# plt.figure(figsize=(6, 6))
# plt.imshow(cm, interpolation='nearest', cmap=plt.cm.Blues)
# plt.title('Confusion Matrix')
# plt.colorbar()
# tick_marks = range(2)
# plt.xticks(tick_marks, ['Loss', 'Win'], rotation=45)
# plt.yticks(tick_marks, ['Loss', 'Win'])

# thresh = cm.max() / 2
# for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
#     plt.text(j, i, cm[i, j], horizontalalignment="center", color="white" if cm[i, j] > thresh else "black")

# plt.tight_layout()
# plt.ylabel('True label')
# plt.xlabel('Predicted label')
# plt.show()

# # Print classification report
# print("Classification Report:\n", classification_report(y_test, y_pred_test_labels, target_names=['Loss', 'Win']))

# # Plot ROC curve
# fpr, tpr, thresholds = roc_curve(y_test, y_pred_test)
# roc_auc = auc(fpr, tpr)

# plt.figure()
# plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (area = {roc_auc:.2f})')
# plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
# plt.xlim([0.0, 1.0])
# plt.ylim([0.0, 1.05])
# plt.xlabel('False Positive Rate')
# plt.ylabel('True Positive Rate')
# plt.title('Receiver Operating Characteristic (ROC)')
# plt.legend(loc="lower right")
# plt.show()

"""### Step 6: Model Saving and Loading

#### Task 6: Save and load the trained model.

This task demonstrates the techniques to persist a trained model using `torch.save` and reload it using `torch.load`. Evaluating the loaded model ensures that it retains its performance, making it practical for deployment in real-world applications.

1. Saving the Model:
- Save the model's learned weights and biases using torch.save().( e.g. , torch.save(model.state_dict(), 'your_model_name.pth'))
- Saving only the state dictionary (model parameters) is preferred because it’s more flexible and efficient than saving the entire model object.

2. Loading the Model:
- Create a new model instance (e.g., `model = LogisticRegressionModel()`) and load the saved parameters. ( e.g. , `model.load_state_dict(torch.load('your_model_name.pth'))`)`.

3. Evaluating the Loaded Model:
   - After loading, set the model to evaluation mode by calling `model.eval()
   - After loading the model, evaluate it again on the test dataset to make sure it performs similarly to when it was first trained..Now evaluate it on the test data.
   - Use `torch.no_grad()` to ensure that no gradients are computed.

#### Exercise 6:

Write code to save the trained model and reload it. Ensure the loaded model performs consistently by evaluating it on the test dataset.

### Step 7: Hyperparameter Tuning

#### Task 7: Perform hyperparameter tuning to find the best learning rate.

By testing different learning rates, you will identify the optimal rate that provides the best test accuracy. This fine-tuning is crucial for enhancing model performance .
1. Define Learning Rates:
   - Choose these learning rates to test ,[0.01, 0.05, 0.1]

2. Reinitialize the Model for Each Learning Rate:
  - For each learning rate, you’ll need to reinitialize the model and optimizer e.g.(`torch.optim.SGD(model.parameters(), lr=lr)`).
   - Each new learning rate requires reinitializing the model since the optimizer and its parameters are linked to the learning rate.

3. Train the Model for Each Learning Rate:
  - Train the model for a fixed number of epochs (e.g., 50 or 100 epochs) for each learning rate, and compute the accuracy on the test set.
  - Track the test accuracy for each learning rate and identify which one yields the best performance.

4. Evaluate and Compare:
  - After training with each learning rate, compare the test accuracy for each configuration.
   - Report the learning rate that gives the highest test accuracy

#### Exercise 7:

Perform hyperparameter tuning to find the best learning rate. Retrain the model for each learning rate and evaluate its performance to identify the optimal rate.

### Step 8: Feature Importance

#### Task 8: Evaluate feature importance to understand the impact of each feature on the prediction.

The code to evaluate feature importance to understand the impact of each feature on the prediction.

 1.Extracting Model Weights:
  - The weights of the logistic regression model represent the importance of each feature in making predictions. These weights are stored in the model's linear layer (`model.linear.weight`).
 - You can extract the weights using `model.linear.weight.data.numpy()` and flatten the resulting tensor to get a 1D array of feature importances.

2.Creating a DataFrame:
 - Create a pandas DataFrame with two columns: one for the feature names and the other for their corresponding importance values (i.e., the learned weights).
 - Ensure the features are aligned with their names in your dataset (e.g., `X_train.columns).

3. Sorting and Plotting Feature Importance:
  - Sort the features based on the absolute value of their importance (weights) to identify the most impactful features.
  - Use a bar plot (via `matplotlib`) to visualize the sorted feature importances, with the feature names on the y-axis and importance values on the x-axis.

4. Interpreting the Results:
  - Larger absolute weights indicate more influential features. Positive weights suggest a positive correlation with the outcome (likely to predict the positive class), while negative weights suggest the opposite.

#### Exercise 8:

Evaluate feature importance by extracting the weights of the linear layer and creating a DataFrame to display the importance of each feature. Visualize the feature importance using a bar plot.
"""

#Use the following code to extract the weight and create dataframe
#Change the name of variables per your code

# Extract the weights of the linear layer:
# weights = model.linear.weight.data.numpy().flatten()
# features = X.columns
# Create a DataFrame for feature importance:
# feature_importance = pd.DataFrame({'Feature': features, 'Importance': weights})
# feature_importance = feature_importance.sort_values(by='Importance', ascending=False)
# print(feature_importance)
# Plot feature importance plt.figure(figsize=(10, 6))
# plt.bar(feature_importance['Feature'], feature_importance['Importance'])
# plt.xlabel('Features')
# plt.ylabel('Importance')
# plt.title('Feature Importance')
# plt.xticks(rotation=45)
# plt.show()

"""# TASK 1
Load the League of Legends dataset and preprocess it for training. Take a screenshot of the code and submit it.
"""

import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

data = pd.read_csv("league_of_legends_data_large.csv")
data.head()

X = data.drop("win", axis=1)
y = data["win"]

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Convert to PyTorch tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32).unsqueeze(1)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32).unsqueeze(1)

print("Task 1 Completed!")

"""# Step 2: Logistic Regression Model

Task 2: Implement a logistic regression model using PyTorch.
Defining the logistic regression model involves specifying the input dimensions, the forward pass using the sigmoid activation function, and initializing the model, loss function, and optimizer.

1 .Define the Logistic Regression Model: Create a class LogisticRegressionModel that inherits from torch.nn.Module.

* In the __init__() method, define a linear layer (nn.Linear) to implement the logistic regression model.
* The forward() method should apply the sigmoid activation function to the output of the linear layer.

2.Initialize the Model, Loss Function, and Optimizer:

* Set input_dim: Use X_train.shape[1] to get the number of features from the training data (X_train).
* Initialize the model: Create an instance of the LogisticRegressionModel class (e.g., model = LogisticRegressionModel())while passing input_dim as a parameter
* Loss Function: Use BCELoss() from torch.nn (Binary Cross-Entropy Loss).
* Optimizer: Initialize the optimizer using optim.SGD() with a learning rate of 0.01

Define the logistic regression model using PyTorch, specifying the input dimensions and the forward pass. Initialize the model, loss function, and optimizer.
"""

import torch.nn as nn
import torch.optim as optim

class LogisticRegressionModel(nn.Module):
    def __init__(self, input_dim):
        super(LogisticRegressionModel, self).__init__()
        self.linear = nn.Linear(input_dim, 1)

    def forward(self, x):
        return torch.sigmoid(self.linear(x))

# Initialize the model, loss function, and optimizer
input_dim = X_train_tensor.shape[1]
model = LogisticRegressionModel(input_dim)
criterion = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

print("Task 2 Completed!")

"""# Step 3: Model Training
Task 3: Train the logistic regression model on the dataset.

The training loop will run for a specified number of epochs. In each epoch, the model makes predictions, calculates the loss, performs backpropagation, and updates the model parameters.

1. Set Number of Epochs:

* Define the number of epochs for training to 1000.

2. Training Loop:
For each epoch:

* Set the model to training mode using model.train().
* Zero the gradients using optimizer.zero_grad().
* Pass the training data (X_train) through the model to get the predictions (outputs).
* Calculate the loss using the defined loss function (criterion).
* Perform backpropagation with loss.backward().
* Update the model's weights using optimizer.step().

3. Print Loss Every 100 Epochs:

* After every 100 epochs, print the current epoch number and the loss value.

4. Model Evaluation:

* Set the model to evaluation mode using model.eval().
* Use torch.no_grad() to ensure no gradients are calculated during evaluation.
* Get predictions on both the training set (X_train) and the test set (X_test).

5. Calculate Accuracy:

* For both the training and test datasets, compute the accuracy by comparing the predicted values with the true values (y_train, y_test).
* Use a threshold of 0.5 for classification

6. Print Accuracy:

* Print the training and test accuracies after the evaluation is complete.
"""

epochs = 1000
# Training loop
for epoch in range(epochs):
    model.train()
    optimizer.zero_grad()  # Zero the gradients

    # Forward pass: Get predictions
    predictions = model(X_train_tensor)

    # Compute the loss
    loss = criterion(predictions, y_train_tensor)

    # Backward pass: Perform backpropagation
    loss.backward()

    # Update the weights
    optimizer.step()

    # Print the loss every 100 epochs
    if (epoch + 1) % 100 == 0:
        print(f"Epoch {epoch+1}/{epochs}, Loss: {loss.item():.4f}")

# Model evaluation
model.eval()
with torch.no_grad():  # No gradients during evaluation

    # Get predictions on the training set
    train_predictions = model(X_train_tensor)
    train_predictions = (train_predictions >= 0.5).float()

    # Get predictions on the test set
    test_predictions = model(X_test_tensor)
    test_predictions = (test_predictions >= 0.5).float()

    # Calculate training accuracy
    train_accuracy = (train_predictions == y_train_tensor).float().mean().item()

    # Calculate test accuracy
    test_accuracy = (test_predictions == y_test_tensor).float().mean().item()

# Print accuracies
print("Training Accuracy: ", train_accuracy)
print("Testing Accuracy: ",test_accuracy)

print("Task 3 Completed!")

"""# Step 4: Model Optimization and Evaluation

## Task 4: Implement optimization techniques and evaluate the model's performance.


Optimization techniques such as L2 regularization (Ridge Regression) help in preventing overfitting. The model is retrained with these optimizations, and its performance is evaluated on both training and testing sets.


**Weight Decay :**In the context of machine learning and specifically in optimization algorithms, weight_decay is a parameter used to apply L2 regularization to the model's parameters (weights). It helps prevent the model from overfitting by penalizing large weight values, thereby encouraging the model to find simpler solutions.To use L2 regularization, you need to modify the optimizer by setting the weight_decay parameter. The weight_decay parameter in the optimizer adds the L2 regularization term during training. For example, when you initialize the optimizer with optim.SGD(model.parameters(), lr=0.01, weight_decay=0.01), the weight_decay=0.01 term applies L2 regularization with a strength of 0.01.

1. Set Up the Optimizer with L2 Regularization:

* Modify the optimizer to include weight_decay for L2 regularization.
* Example:
optimizer = optim.SGD(model.parameters(), lr=0.01, weight_decay=0.01)

2. Train the Model with L2 Regularization:

* Follow the same steps as before but use the updated optimizer with regularization during training.
* Use epochs=1000

3. Evaluate the Optimized Model:

* After training, evaluate the model on both the training and test datasets.
* Compute the accuracy for both sets by comparing the model's predictions to the true labels (y_train and y_test).

4. Calculate and Print the Accuracy:

* Use a threshold of 0.5 to determine whether the model's predictions are class 0 or class 1.
* Print the training accuracy and test accuracy after evaluation.
* Exercise 4:
Implement optimization techniques like L2 regularization and retrain the model. Evaluate the performance of the optimized model on both training and testing sets.
"""

# Modify the optimizer to include L2 regularization (weight_decay)
l2_weight_decay = 0.01
optimizer = optim.SGD(model.parameters(), lr=0.01, weight_decay=l2_weight_decay)

# Set the number of epochs
epochs = 1000

# Training loop with L2 regularization
for epoch in range(epochs):
    model.train()
    optimizer.zero_grad()  # Zero the gradients

    # Forward pass: Get predictions
    predictions = model(X_train_tensor)

    # Compute the loss
    loss = criterion(predictions, y_train_tensor)

    # Backward pass: Perform backpropagation
    loss.backward()

    # Update the weights
    optimizer.step()

    # Print the loss every 100 epochs
    if (epoch + 1) % 100 == 0:
        print(f"Epoch {epoch+1}/{epochs}, Loss: {loss.item():.4f}")

# Evaluate the optimized model
model.eval()
with torch.no_grad():  # No gradients during evaluation

    # Get predictions on the training set
    train_predictions = model(X_train_tensor)
    train_predictions = (train_predictions >= 0.5).float()

    # Get predictions on the test set
    test_predictions = model(X_test_tensor)
    test_predictions = (test_predictions >= 0.5).float()

    # Calculate training accuracy
    train_accuracy = (train_predictions == y_train_tensor).float().mean().item()

    # Calculate test accuracy
    test_accuracy = (test_predictions == y_test_tensor).float().mean().item()

# Print accuracies
print("Training Accuracy with L2 Regularization: ",train_accuracy)
print("Testing Accuracy with L2 Regularization: ",test_accuracy)

print("Task 4 Completed!")

"""# Step 5: Visualization and Interpretation

Visualization tools like confusion matrices and ROC curves provide insights into the model's performance. The confusion matrix helps in understanding the classification accuracy, while the ROC curve illustrates the trade-off between sensitivity and specificity.

Confusion Matrix : A Confusion Matrix is a fundamental tool used in classification problems to evaluate the performance of a model. It provides a matrix showing the number of correct and incorrect predictions made by the model, categorized by the actual and predicted classes. Where

* True Positive (TP): Correctly predicted positive class (class 1).
* True Negative (TN): Correctly predicted negative class (class 0).
* False Positive (FP): Incorrectly predicted as positive (class 1), but the actual class is negative (class 0). This is also called a Type I error.

False Negative (FN): Incorrectly predicted as negative (class 0), but the actual class is positive (class 1). This is also called a Type II error.


ROC Curve (Receiver Operating Characteristic Curve): The ROC Curve is a graphical representation used to evaluate the performance of a binary classification model across all classification thresholds. It plots two metrics:

* True Positive Rate (TPR) or Recall (Sensitivity)-It is the proportion of actual positive instances (class 1) that were correctly classified as positive by the model.
* False Positive Rate (FPR)-It is the proportion of actual negative instances (class 0) that were incorrectly classified as positive by the model.


AUC: AUC stands for Area Under the Curve and is a performance metric used to evaluate the quality of a binary classification model. Specifically, it refers to the area under the ROC curve (Receiver Operating Characteristic curve), which plots the True Positive Rate (TPR) versus the False Positive Rate (FPR) for different threshold values.



Classification Report: A Classification Report is a summary of various classification metrics, which are useful for evaluating the performance of a classifier on the given dataset.
"""

import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report, roc_curve, auc
import itertools

# Make predictions
y_pred_test = model(X_test_tensor)

# Convert probabilities to labels (binary classification: 0 or 1)
y_pred_test_labels = (y_pred_test > 0.5).float()

# Visualize the confusion matrix
cm = confusion_matrix(y_test_tensor.numpy(), y_pred_test_labels.numpy())

plt.figure(figsize=(6, 6))
plt.imshow(cm, interpolation='nearest', cmap=plt.cm.Blues)
plt.title('Confusion Matrix')
plt.colorbar()
tick_marks = range(2)
plt.xticks(tick_marks, ['Loss', 'Win'], rotation=45)
plt.yticks(tick_marks, ['Loss', 'Win'])

thresh = cm.max() / 2
for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
    plt.text(j, i, cm[i, j], horizontalalignment="center", color="white" if cm[i, j] > thresh else "black")

plt.tight_layout()
plt.ylabel('True label')
plt.xlabel('Predicted label')
plt.show()

#  Print classification report
print("Classification Report:\n", classification_report(y_test_tensor.numpy(), y_pred_test_labels.numpy(), target_names=['Loss', 'Win']))

# Plot ROC curve
fpr, tpr, thresholds = roc_curve(y_test_tensor.detach().numpy(), y_pred_test.detach().numpy())
roc_auc = auc(fpr, tpr)

plt.figure()
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (area = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC)')
plt.legend(loc="lower right")
plt.show()

print("Task 5 Completed!")

"""# Task 6: Save and load the trained model.


This task demonstrates the techniques to persist a trained model using torch.save and reload it using torch.load. Evaluating the loaded model ensures that it retains its performance, making it practical for deployment in real-world applications.

* Saving the Model:
Save the model's learned weights and biases using torch.save().( e.g. , torch.save(model.state_dict(), 'your_model_name.pth'))
Saving only the state dictionary (model parameters) is preferred because it’s more flexible and efficient than saving the entire model object.
* Loading the Model:
Create a new model instance (e.g., model = LogisticRegressionModel()) and load the saved parameters. ( e.g. , model.load_state_dict(torch.load('your_model_name.pth')))`.
* Evaluating the Loaded Model:
After loading, set the model to evaluation mode by calling `model.eval()
After loading the model, evaluate it again on the test dataset to make sure it performs similarly to when it was first trained..Now evaluate it on the test data.
Use torch.no_grad() to ensure that no gradients are computed.
"""

## Write your code here
# Save the model
torch.save(model.state_dict(), "logistic_model.pth")
print("Model saved!")

# Load the model
loaded_model = LogisticRegressionModel(input_dim)
loaded_model.load_state_dict(torch.load("logistic_model.pth"))
print("Model loaded!")


# Ensure the loaded model is in evaluation mode
loaded_model.eval()


# Evaluate the loaded model
with torch.no_grad():
    loaded_test_predictions = loaded_model(X_test_tensor)
    loaded_test_predictions = (loaded_test_predictions >= 0.5).float()
    loaded_accuracy = (loaded_test_predictions == y_test_tensor).float().mean()

print("Loaded Model Test Accuracy: ",loaded_accuracy.item())

"""# Step 7: Hyperparameter Tuning
Task 7: Perform hyperparameter tuning to find the best learning rate.
By testing different learning rates, you will identify the optimal rate that provides the best test accuracy. This fine-tuning is crucial for enhancing model performance .

* Define Learning Rates:

Choose these learning rates to test ,[0.01, 0.05, 0.1]
Reinitialize the Model for Each Learning Rate:

For each learning rate, you’ll need to reinitialize the model and optimizer e.g.(torch.optim.SGD(model.parameters(), lr=lr)).
Each new learning rate requires reinitializing the model since the optimizer and its parameters are linked to the learning rate.
* Train the Model for Each Learning Rate:
Train the model for a fixed number of epochs (e.g., 50 or 100 epochs) for each learning rate, and compute the accuracy on the test set.
Track the test accuracy for each learning rate and identify which one yields the best performance.
* Evaluate and Compare:
After training with each learning rate, compare the test accuracy for each configuration.
Report the learning rate that gives the highest test accuracy
"""

# Define learning rates to test
learning_rates = [0.01, 0.05, 0.1]

#  Initialize an empty dictionary to store results
learning_rate_results = {}

# Train and evaluate the model for each learning rate
for lr in learning_rates:
    print(f"Training with learning rate: {lr}")

    # Reinitialize the model and optimizer
    model = LogisticRegressionModel(input_dim)
    optimizer = torch.optim.SGD(model.parameters(), lr=lr)
    criterion = nn.BCELoss()

    # Train the model
    num_epochs = 50  # or 100 epochs
    for epoch in range(num_epochs):
        model.train()
        optimizer.zero_grad()
        output = model(X_train_tensor)
        loss = criterion(output, y_train_tensor)
        loss.backward()
        optimizer.step()

    # Evaluate the model on the test set
    model.eval()
    with torch.no_grad():
        predictions = model(X_test_tensor)
        predictions = (predictions >= 0.5).float()  # Convert probabilities to class labels
        accuracy = (predictions == y_test_tensor).float().mean()

    # Store the test accuracy for this learning rate
    learning_rate_results[lr] = accuracy.item()

    print("Test Accuracy with learning rate ", lr, ":", accuracy.item())

# Identify the best learning rate
best_lr = max(learning_rate_results, key=learning_rate_results.get)
best_accuracy = learning_rate_results[best_lr]

print("Best learning rate is", best_lr,"with highest test accuracy:", best_accuracy)

"""# Step 8: Feature Importance
Task 8: Evaluate feature importance to understand the impact of each feature on the prediction.
The code to evaluate feature importance to understand the impact of each feature on the prediction.

1.Extracting Model Weights:

* The weights of the logistic regression model represent the importance of each feature in making predictions. These weights are stored in the model's linear layer (model.linear.weight).
* You can extract the weights using model.linear.weight.data.numpy() and flatten the resulting tensor to get a 1D array of feature importances.

2.Creating a DataFrame:

* Create a pandas DataFrame with two columns: one for the feature names and the other for their corresponding importance values (i.e., the learned weights).
Ensure the features are aligned with their names in your dataset (e.g., `X_train.columns).
* Sorting and Plotting Feature Importance:
Sort the features based on the absolute value of their importance (weights) to identify the most impactful features.
* Use a bar plot (via matplotlib) to visualize the sorted feature importances, with the feature names on the y-axis and importance values on the x-axis.
* Interpreting the Results:
Larger absolute weights indicate more influential features. Positive weights suggest a positive correlation with the outcome (likely to predict the positive class), while negative weights suggest the opposite.
"""

import pandas as pd
import matplotlib.pyplot as plt

# Extract the weights of the linear layer
## Write your code here
weights = model.linear.weight.data.numpy().flatten()  # Flatten the weights to get a 1D array
features = X.columns  # Assuming you are using a DataFrame for X_train

# Create a DataFrame for feature importance
## Write your code here
feature_importance = pd.DataFrame({'Feature': features, 'Importance': weights})
feature_importance = feature_importance.sort_values(by='Importance', ascending=False)

print(feature_importance)

# Plot feature importance
plt.figure(figsize=(10, 6))
plt.barh(feature_importance['Feature'], feature_importance['Importance'])
plt.xlabel('Importance')
plt.ylabel('Features')
plt.title('Feature Importance')
plt.show()